# Pembacaan Data dari CSV

In [1]:
%cat contoh-data-data-mining.csv

Time,Age,Name,Sentiment
2017/3/14 8:34:48,41,Anton,negative
2017/10/5 9:56:51,31,Budi,positive
2018/6/15 14:28:5,22,Charlie,positive
2018/6/5 17:36:32,18,Dedi,positive
2018/9/25 7:46:23,12,Edy,negative
2019/7/4 20:11:33,43,Feris,positive
2017/11/24 8:58:27,49,Galah,negative
2019/12/14 15:15:41,13,Halimah,positive
2018/12/1 5:37:10,30,Intan,negative
2017/10/14 23:25:42,47,Jack,positive
2017/4/13 9:37:6,47,Kirun,positive
2019/3/13 12:43:35,29,Lala,positive
2019/8/14 17:32:8,18,Miftah,positive
2018/4/21 16:12:40,29,Nono,positive
2018/11/23 2:18:59,28,Ono,negative
2017/1/25 20:1:4,41,Pras,positive
2017/12/8 6:1:21,27,Qori,negative
2017/12/3 18:0:44,46,Raras,positive
2019/8/24 17:25:58,38,Smith,positive
2018/9/10 3:59:15,12,Tim,negative
2019/12/14 5:28:8,49,Uvwevwe,negative
2019/4/6 14:51:26,42,Victor,positive
2019/5/4 21:41:19,10,Wendy,positive
2019/2/28 11:56:35,18,Xavier,positive
2018/8/26 6:16:44,33,Yono,negative
2018/6/24 5:7:25,37,Zakir,negative
2019/7/7 11:25:7,18,Adinda,positive
2019/2/15 6:37:14,28,Beatrix,negative
2017/1/1 12:43:7,32,Corry,positive
2017/1/22 19:52:30,26,Dodit,positive
2017/10/1 23:51:53,28,Ega,positive
2018/11/4 4:48:58,25,Frans,negative
2018/1/18 5:52:47,19,Anton,negative
2017/12/23 14:28:21,43,Budi,positive
2018/11/14 5:57:18,15,Charlie,negative
2017/11/25 15:43:56,14,Dedi,positive
2018/1/2 4:29:59,50,Edy,negative
2018/11/21 6:39:48,26,Feris,negative
2018/10/14 8:50:6,38,Galah,negative
2017/5/7 23:32:47,49,Halimah,positive
2017/1/3 16:41:35,10,Intan,positive
2019/8/17 8:11:58,10,Jack,positive
2017/7/8 1:53:13,48,Kirun,negative
2019/2/18 4:7:52,37,Lala,negative
2018/7/26 21:37:35,10,Miftah,positive
2019/11/22 21:33:49,37,Nono,positive
2019/11/6 8:57:15,42,Ono,negative
2019/7/9 0:14:59,50,Pras,negative
2019/8/1 12:30:10,41,Qori,positive
2017/6/7 10:54:43,49,Raras,positive
2017/12/14 2:3:48,27,Smith,negative
2019/12/23 21:46:0,38,Tim,positive
2018/1/25 15:30:48,13,Uvwevwe,positive
2017/5/15 4:38:5,46,Victor,negative
2018/2/28 20:3:57,42,Wendy,positive
2019/3/22 18:14:21,28,Xavier,positive
2018/9/12 7:11:20,39,Yono,negative
2018/4/8 5:36:56,38,Zakir,negative
2018/11/25 8:1:58,31,Adinda,negative
2019/2/17 12:53:39,32,Beatrix,positive
2019/2/2 20:18:11,17,Corry,positive
2017/9/8 22:33:0,13,Dodit,positive
2019/8/7 3:53:41,16,Ega,negative
2017/4/21 9:21:52,33,Frans,positive
2019/4/14 18:50:46,45,Anton,positive
2017/10/19 21:56:0,45,Budi,positive
2017/2/13 13:19:20,35,Charlie,positive
2019/8/19 19:52:7,50,Dedi,positive
2017/1/11 19:46:9,36,Edy,positive
2017/8/25 14:42:22,30,Feris,positive
2018/6/4 3:11:55,17,Galah,negative
2017/10/2 6:15:35,46,Halimah,negative
2017/2/15 1:10:53,36,Intan,negative
2018/1/5 16:34:19,25,Jack,positive
2017/12/21 10:41:2,31,Kirun,positive
?/7/15 9:41:3,23,Lala,positive
2018/5/2 13:57:30,43,Miftah,positive
2018/1/20 23:40:31,44,Nono,positive
2018/2/27 23:23:20,21,Ono,positive
2018/8/12 21:?:20,11,Pras,positive
2017/1/26 5:6:5,29,Qori,negative
2019/12/11 10:55:16,41,Raras,positive
2018/4/9 4:30:48,50,Smith,negative
2018/5/10 5:9:27,?,Tim,negative
2019/4/27 4:39:34,16,Uvwevwe,negative
2018/6/26 7:2:57,36,Victor,negative
2018/9/6 4:42:59,13,Wendy,negative
2018/10/1 3:15:55,41,Xavier,?
2019/1/2 20:52:52,44,Yono,positive
2017/12/24 1:19:7,10,Zakir,negative
2018/2/6 13:47:11,37,Adinda,positive
2017/9/19 9:30:48,150,Beatrix,positive
2019/11/14 5:41:6,31,Corry,negative
2017/12/15 11:44:25,34,?,positive
2019/3/10 0:41:34,42,Ega,negative
2017/3/11 8:10:58,12,Frans,positive
2018/9/17 9:12:59,26,Anton,positive
2019/4/13 18:55:54,23,Budi,positive
2018/2/20 3:18:26,28,Charlie,negative
2017/4/23 13:53:6,20,Dedi,positive

## Pakai pandas

In [24]:
import pandas
df = pandas.read_csv('contoh-data-data-mining.csv')
df

                   Time  Age     Name Sentiment
0     2017/3/14 8:34:48   41    Anton  negative
1     2017/10/5 9:56:51   31     Budi  positive
2     2018/6/15 14:28:5   22  Charlie  positive
3     2018/6/5 17:36:32   18     Dedi  positive
4     2018/9/25 7:46:23   12      Edy  negative
5     2019/7/4 20:11:33   43    Feris  positive
6    2017/11/24 8:58:27   49    Galah  negative
7   2019/12/14 15:15:41   13  Halimah  positive
8     2018/12/1 5:37:10   30    Intan  negative
9   2017/10/14 23:25:42   47     Jack  positive
10     2017/4/13 9:37:6   47    Kirun  positive
11   2019/3/13 12:43:35   29     Lala  positive
12    2019/8/14 17:32:8   18   Miftah  positive
13   2018/4/21 16:12:40   29     Nono  positive
14   2018/11/23 2:18:59   28      Ono  negative
15     2017/1/25 20:1:4   41     Pras  positive
16     2017/12/8 6:1:21   27     Qori  negative
17    2017/12/3 18:0:44   46    Raras  positive
18   2019/8/24 17:25:58   38    Smith  positive
19    2018/9/10 3:59:15   12      Tim  negative
20    2019/12/14 5:28:8   49  Uvwevwe  negative
21    2019/4/6 14:51:26   42   Victor  positive
22    2019/5/4 21:41:19   10    Wendy  positive
23   2019/2/28 11:56:35   18   Xavier  positive
24    2018/8/26 6:16:44   33     Yono  negative
25     2018/6/24 5:7:25   37    Zakir  negative
26     2019/7/7 11:25:7   18   Adinda  positive
27    2019/2/15 6:37:14   28  Beatrix  negative
28     2017/1/1 12:43:7   32    Corry  positive
29   2017/1/22 19:52:30   26    Dodit  positive
..                  ...  ...      ...       ...
70     2018/6/4 3:11:55   17    Galah  negative
71    2017/10/2 6:15:35   46  Halimah  negative
72    2017/2/15 1:10:53   36    Intan  negative
73    2018/1/5 16:34:19   25     Jack  positive
74   2017/12/21 10:41:2   31    Kirun  positive
75        ?/7/15 9:41:3   23     Lala  positive
76    2018/5/2 13:57:30   43   Miftah  positive
77   2018/1/20 23:40:31   44     Nono  positive
78   2018/2/27 23:23:20   21      Ono  positive
79    2018/8/12 21:?:20   11     Pras  positive
80      2017/1/26 5:6:5   29     Qori  negative
81  2019/12/11 10:55:16   41    Raras  positive
82     2018/4/9 4:30:48   50    Smith  negative
83     2018/5/10 5:9:27    ?      Tim  negative
84    2019/4/27 4:39:34   16  Uvwevwe  negative
85     2018/6/26 7:2:57   36   Victor  negative
86     2018/9/6 4:42:59   13    Wendy  negative
87    2018/10/1 3:15:55   41   Xavier         ?
88    2019/1/2 20:52:52   44     Yono  positive
89    2017/12/24 1:19:7   10    Zakir  negative
90    2018/2/6 13:47:11   37   Adinda  positive
91    2017/9/19 9:30:48  150  Beatrix  positive
92    2019/11/14 5:41:6   31    Corry  negative
93  2017/12/15 11:44:25   34        ?  positive
94    2019/3/10 0:41:34   42      Ega  negative
95    2017/3/11 8:10:58   12    Frans  positive
96    2018/9/17 9:12:59   26    Anton  positive
97   2019/4/13 18:55:54   23     Budi  positive
98    2018/2/20 3:18:26   28  Charlie  negative
99    2017/4/23 13:53:6   20     Dedi  positive

[100 rows x 4 columns]

In [25]:
df.describe()

                     Time  Age   Name Sentiment
count                 100  100    100       100
unique                100   41     33         3
top     2018/11/4 4:48:58   28  Anton  positive
freq                    1    5      4        59

In [26]:
df.corr()

Empty DataFrame
Columns: []
Index: []

In [27]:
df = df[['Time', 'Age', 'Sentiment']]
df

                   Time  Age Sentiment
0     2017/3/14 8:34:48   41  negative
1     2017/10/5 9:56:51   31  positive
2     2018/6/15 14:28:5   22  positive
3     2018/6/5 17:36:32   18  positive
4     2018/9/25 7:46:23   12  negative
5     2019/7/4 20:11:33   43  positive
6    2017/11/24 8:58:27   49  negative
7   2019/12/14 15:15:41   13  positive
8     2018/12/1 5:37:10   30  negative
9   2017/10/14 23:25:42   47  positive
10     2017/4/13 9:37:6   47  positive
11   2019/3/13 12:43:35   29  positive
12    2019/8/14 17:32:8   18  positive
13   2018/4/21 16:12:40   29  positive
14   2018/11/23 2:18:59   28  negative
15     2017/1/25 20:1:4   41  positive
16     2017/12/8 6:1:21   27  negative
17    2017/12/3 18:0:44   46  positive
18   2019/8/24 17:25:58   38  positive
19    2018/9/10 3:59:15   12  negative
20    2019/12/14 5:28:8   49  negative
21    2019/4/6 14:51:26   42  positive
22    2019/5/4 21:41:19   10  positive
23   2019/2/28 11:56:35   18  positive
24    2018/8/26 6:16:44   33  negative
25     2018/6/24 5:7:25   37  negative
26     2019/7/7 11:25:7   18  positive
27    2019/2/15 6:37:14   28  negative
28     2017/1/1 12:43:7   32  positive
29   2017/1/22 19:52:30   26  positive
..                  ...  ...       ...
70     2018/6/4 3:11:55   17  negative
71    2017/10/2 6:15:35   46  negative
72    2017/2/15 1:10:53   36  negative
73    2018/1/5 16:34:19   25  positive
74   2017/12/21 10:41:2   31  positive
75        ?/7/15 9:41:3   23  positive
76    2018/5/2 13:57:30   43  positive
77   2018/1/20 23:40:31   44  positive
78   2018/2/27 23:23:20   21  positive
79    2018/8/12 21:?:20   11  positive
80      2017/1/26 5:6:5   29  negative
81  2019/12/11 10:55:16   41  positive
82     2018/4/9 4:30:48   50  negative
83     2018/5/10 5:9:27    ?  negative
84    2019/4/27 4:39:34   16  negative
85     2018/6/26 7:2:57   36  negative
86     2018/9/6 4:42:59   13  negative
87    2018/10/1 3:15:55   41         ?
88    2019/1/2 20:52:52   44  positive
89    2017/12/24 1:19:7   10  negative
90    2018/2/6 13:47:11   37  positive
91    2017/9/19 9:30:48  150  positive
92    2019/11/14 5:41:6   31  negative
93  2017/12/15 11:44:25   34  positive
94    2019/3/10 0:41:34   42  negative
95    2017/3/11 8:10:58   12  positive
96    2018/9/17 9:12:59   26  positive
97   2019/4/13 18:55:54   23  positive
98    2018/2/20 3:18:26   28  negative
99    2017/4/23 13:53:6   20  positive

[100 rows x 3 columns]

In [28]:
def getDatePartOnly(dateTime):
    return dateTime.split(' ')[0]
def getTimePartOnly(dateTime):
    return dateTime.split(' ')[1]
    
def getYearOnly(dateTime):
    return getDatePartOnly(dateTime).split('/')[0]
def getMonthOnly(dateTime):
    return getDatePartOnly(dateTime).split('/')[1]
def getDateOnly(dateTime):
    return getDatePartOnly(dateTime).split('/')[2]
    
def getHourOnly(dateTime):
    return getTimePartOnly(dateTime).split(':')[0]
def getMinuteOnly(dateTime):
    return getTimePartOnly(dateTime).split(':')[1]
def getSecondOnly(dateTime):
    return getTimePartOnly(dateTime).split(':')[2]

df['Year'] = df['Time'].apply(getYearOnly)
df['Month'] = df['Time'].apply(getMonthOnly)
df['Date'] = df['Time'].apply(getDateOnly)
df['Hour'] = df['Time'].apply(getHourOnly)
df['Minute'] = df['Time'].apply(getMinuteOnly)
df['Second'] = df['Time'].apply(getSecondOnly)
df

                   Time  Age Sentiment  Year Month Date Hour Minute Second
0     2017/3/14 8:34:48   41  negative  2017     3   14    8     34     48
1     2017/10/5 9:56:51   31  positive  2017    10    5    9     56     51
2     2018/6/15 14:28:5   22  positive  2018     6   15   14     28      5
3     2018/6/5 17:36:32   18  positive  2018     6    5   17     36     32
4     2018/9/25 7:46:23   12  negative  2018     9   25    7     46     23
5     2019/7/4 20:11:33   43  positive  2019     7    4   20     11     33
6    2017/11/24 8:58:27   49  negative  2017    11   24    8     58     27
7   2019/12/14 15:15:41   13  positive  2019    12   14   15     15     41
8     2018/12/1 5:37:10   30  negative  2018    12    1    5     37     10
9   2017/10/14 23:25:42   47  positive  2017    10   14   23     25     42
10     2017/4/13 9:37:6   47  positive  2017     4   13    9     37      6
11   2019/3/13 12:43:35   29  positive  2019     3   13   12     43     35
12    2019/8/14 17:32:8   18  positive  2019     8   14   17     32      8
13   2018/4/21 16:12:40   29  positive  2018     4   21   16     12     40
14   2018/11/23 2:18:59   28  negative  2018    11   23    2     18     59
15     2017/1/25 20:1:4   41  positive  2017     1   25   20      1      4
16     2017/12/8 6:1:21   27  negative  2017    12    8    6      1     21
17    2017/12/3 18:0:44   46  positive  2017    12    3   18      0     44
18   2019/8/24 17:25:58   38  positive  2019     8   24   17     25     58
19    2018/9/10 3:59:15   12  negative  2018     9   10    3     59     15
20    2019/12/14 5:28:8   49  negative  2019    12   14    5     28      8
21    2019/4/6 14:51:26   42  positive  2019     4    6   14     51     26
22    2019/5/4 21:41:19   10  positive  2019     5    4   21     41     19
23   2019/2/28 11:56:35   18  positive  2019     2   28   11     56     35
24    2018/8/26 6:16:44   33  negative  2018     8   26    6     16     44
25     2018/6/24 5:7:25   37  negative  2018     6   24    5      7     25
26     2019/7/7 11:25:7   18  positive  2019     7    7   11     25      7
27    2019/2/15 6:37:14   28  negative  2019     2   15    6     37     14
28     2017/1/1 12:43:7   32  positive  2017     1    1   12     43      7
29   2017/1/22 19:52:30   26  positive  2017     1   22   19     52     30
..                  ...  ...       ...   ...   ...  ...  ...    ...    ...
70     2018/6/4 3:11:55   17  negative  2018     6    4    3     11     55
71    2017/10/2 6:15:35   46  negative  2017    10    2    6     15     35
72    2017/2/15 1:10:53   36  negative  2017     2   15    1     10     53
73    2018/1/5 16:34:19   25  positive  2018     1    5   16     34     19
74   2017/12/21 10:41:2   31  positive  2017    12   21   10     41      2
75        ?/7/15 9:41:3   23  positive     ?     7   15    9     41      3
76    2018/5/2 13:57:30   43  positive  2018     5    2   13     57     30
77   2018/1/20 23:40:31   44  positive  2018     1   20   23     40     31
78   2018/2/27 23:23:20   21  positive  2018     2   27   23     23     20
79    2018/8/12 21:?:20   11  positive  2018     8   12   21      ?     20
80      2017/1/26 5:6:5   29  negative  2017     1   26    5      6      5
81  2019/12/11 10:55:16   41  positive  2019    12   11   10     55     16
82     2018/4/9 4:30:48   50  negative  2018     4    9    4     30     48
83     2018/5/10 5:9:27    ?  negative  2018     5   10    5      9     27
84    2019/4/27 4:39:34   16  negative  2019     4   27    4     39     34
85     2018/6/26 7:2:57   36  negative  2018     6   26    7      2     57
86     2018/9/6 4:42:59   13  negative  2018     9    6    4     42     59
87    2018/10/1 3:15:55   41         ?  2018    10    1    3     15     55
88    2019/1/2 20:52:52   44  positive  2019     1    2   20     52     52
89    2017/12/24 1:19:7   10  negative  2017    12   24    1     19      7
90    2018/2/6 13:47:11   37  positive  2018     2    6   13     47     11
91    2017/9/19 9:30:48  150  positive  2017     9   19    9     30     48
92    2019/11/14 5:41:6   31  negative  2019    11   14    5     41      6
93  2017/12/15 11:44:25   34  positive  2017    12   15   11     44     25
94    2019/3/10 0:41:34   42  negative  2019     3   10    0     41     34
95    2017/3/11 8:10:58   12  positive  2017     3   11    8     10     58
96    2018/9/17 9:12:59   26  positive  2018     9   17    9     12     59
97   2019/4/13 18:55:54   23  positive  2019     4   13   18     55     54
98    2018/2/20 3:18:26   28  negative  2018     2   20    3     18     26
99    2017/4/23 13:53:6   20  positive  2017     4   23   13     53      6

[100 rows x 9 columns]

In [29]:
def turnToNone(val):
    return None if val == '?' else val
for field in ['Age', 'Sentiment', 'Year', 'Month', 'Date', 'Hour', 'Minute', 'Date']:
    df[field] = df[field].apply(turnToNone)
df

                   Time   Age Sentiment  Year Month Date Hour Minute Second
0     2017/3/14 8:34:48    41  negative  2017     3   14    8     34     48
1     2017/10/5 9:56:51    31  positive  2017    10    5    9     56     51
2     2018/6/15 14:28:5    22  positive  2018     6   15   14     28      5
3     2018/6/5 17:36:32    18  positive  2018     6    5   17     36     32
4     2018/9/25 7:46:23    12  negative  2018     9   25    7     46     23
5     2019/7/4 20:11:33    43  positive  2019     7    4   20     11     33
6    2017/11/24 8:58:27    49  negative  2017    11   24    8     58     27
7   2019/12/14 15:15:41    13  positive  2019    12   14   15     15     41
8     2018/12/1 5:37:10    30  negative  2018    12    1    5     37     10
9   2017/10/14 23:25:42    47  positive  2017    10   14   23     25     42
10     2017/4/13 9:37:6    47  positive  2017     4   13    9     37      6
11   2019/3/13 12:43:35    29  positive  2019     3   13   12     43     35
12    2019/8/14 17:32:8    18  positive  2019     8   14   17     32      8
13   2018/4/21 16:12:40    29  positive  2018     4   21   16     12     40
14   2018/11/23 2:18:59    28  negative  2018    11   23    2     18     59
15     2017/1/25 20:1:4    41  positive  2017     1   25   20      1      4
16     2017/12/8 6:1:21    27  negative  2017    12    8    6      1     21
17    2017/12/3 18:0:44    46  positive  2017    12    3   18      0     44
18   2019/8/24 17:25:58    38  positive  2019     8   24   17     25     58
19    2018/9/10 3:59:15    12  negative  2018     9   10    3     59     15
20    2019/12/14 5:28:8    49  negative  2019    12   14    5     28      8
21    2019/4/6 14:51:26    42  positive  2019     4    6   14     51     26
22    2019/5/4 21:41:19    10  positive  2019     5    4   21     41     19
23   2019/2/28 11:56:35    18  positive  2019     2   28   11     56     35
24    2018/8/26 6:16:44    33  negative  2018     8   26    6     16     44
25     2018/6/24 5:7:25    37  negative  2018     6   24    5      7     25
26     2019/7/7 11:25:7    18  positive  2019     7    7   11     25      7
27    2019/2/15 6:37:14    28  negative  2019     2   15    6     37     14
28     2017/1/1 12:43:7    32  positive  2017     1    1   12     43      7
29   2017/1/22 19:52:30    26  positive  2017     1   22   19     52     30
..                  ...   ...       ...   ...   ...  ...  ...    ...    ...
70     2018/6/4 3:11:55    17  negative  2018     6    4    3     11     55
71    2017/10/2 6:15:35    46  negative  2017    10    2    6     15     35
72    2017/2/15 1:10:53    36  negative  2017     2   15    1     10     53
73    2018/1/5 16:34:19    25  positive  2018     1    5   16     34     19
74   2017/12/21 10:41:2    31  positive  2017    12   21   10     41      2
75        ?/7/15 9:41:3    23  positive  None     7   15    9     41      3
76    2018/5/2 13:57:30    43  positive  2018     5    2   13     57     30
77   2018/1/20 23:40:31    44  positive  2018     1   20   23     40     31
78   2018/2/27 23:23:20    21  positive  2018     2   27   23     23     20
79    2018/8/12 21:?:20    11  positive  2018     8   12   21   None     20
80      2017/1/26 5:6:5    29  negative  2017     1   26    5      6      5
81  2019/12/11 10:55:16    41  positive  2019    12   11   10     55     16
82     2018/4/9 4:30:48    50  negative  2018     4    9    4     30     48
83     2018/5/10 5:9:27  None  negative  2018     5   10    5      9     27
84    2019/4/27 4:39:34    16  negative  2019     4   27    4     39     34
85     2018/6/26 7:2:57    36  negative  2018     6   26    7      2     57
86     2018/9/6 4:42:59    13  negative  2018     9    6    4     42     59
87    2018/10/1 3:15:55    41      None  2018    10    1    3     15     55
88    2019/1/2 20:52:52    44  positive  2019     1    2   20     52     52
89    2017/12/24 1:19:7    10  negative  2017    12   24    1     19      7
90    2018/2/6 13:47:11    37  positive  2018     2    6   13     47     11
91    2017/9/19 9:30:48   150  positive  2017     9   19    9     30     48
92    2019/11/14 5:41:6    31  negative  2019    11   14    5     41      6
93  2017/12/15 11:44:25    34  positive  2017    12   15   11     44     25
94    2019/3/10 0:41:34    42  negative  2019     3   10    0     41     34
95    2017/3/11 8:10:58    12  positive  2017     3   11    8     10     58
96    2018/9/17 9:12:59    26  positive  2018     9   17    9     12     59
97   2019/4/13 18:55:54    23  positive  2019     4   13   18     55     54
98    2018/2/20 3:18:26    28  negative  2018     2   20    3     18     26
99    2017/4/23 13:53:6    20  positive  2017     4   23   13     53      6

[100 rows x 9 columns]

In [30]:
df = df.dropna()
df

                   Time  Age Sentiment  Year Month Date Hour Minute Second
0     2017/3/14 8:34:48   41  negative  2017     3   14    8     34     48
1     2017/10/5 9:56:51   31  positive  2017    10    5    9     56     51
2     2018/6/15 14:28:5   22  positive  2018     6   15   14     28      5
3     2018/6/5 17:36:32   18  positive  2018     6    5   17     36     32
4     2018/9/25 7:46:23   12  negative  2018     9   25    7     46     23
5     2019/7/4 20:11:33   43  positive  2019     7    4   20     11     33
6    2017/11/24 8:58:27   49  negative  2017    11   24    8     58     27
7   2019/12/14 15:15:41   13  positive  2019    12   14   15     15     41
8     2018/12/1 5:37:10   30  negative  2018    12    1    5     37     10
9   2017/10/14 23:25:42   47  positive  2017    10   14   23     25     42
10     2017/4/13 9:37:6   47  positive  2017     4   13    9     37      6
11   2019/3/13 12:43:35   29  positive  2019     3   13   12     43     35
12    2019/8/14 17:32:8   18  positive  2019     8   14   17     32      8
13   2018/4/21 16:12:40   29  positive  2018     4   21   16     12     40
14   2018/11/23 2:18:59   28  negative  2018    11   23    2     18     59
15     2017/1/25 20:1:4   41  positive  2017     1   25   20      1      4
16     2017/12/8 6:1:21   27  negative  2017    12    8    6      1     21
17    2017/12/3 18:0:44   46  positive  2017    12    3   18      0     44
18   2019/8/24 17:25:58   38  positive  2019     8   24   17     25     58
19    2018/9/10 3:59:15   12  negative  2018     9   10    3     59     15
20    2019/12/14 5:28:8   49  negative  2019    12   14    5     28      8
21    2019/4/6 14:51:26   42  positive  2019     4    6   14     51     26
22    2019/5/4 21:41:19   10  positive  2019     5    4   21     41     19
23   2019/2/28 11:56:35   18  positive  2019     2   28   11     56     35
24    2018/8/26 6:16:44   33  negative  2018     8   26    6     16     44
25     2018/6/24 5:7:25   37  negative  2018     6   24    5      7     25
26     2019/7/7 11:25:7   18  positive  2019     7    7   11     25      7
27    2019/2/15 6:37:14   28  negative  2019     2   15    6     37     14
28     2017/1/1 12:43:7   32  positive  2017     1    1   12     43      7
29   2017/1/22 19:52:30   26  positive  2017     1   22   19     52     30
..                  ...  ...       ...   ...   ...  ...  ...    ...    ...
66   2017/2/13 13:19:20   35  positive  2017     2   13   13     19     20
67    2019/8/19 19:52:7   50  positive  2019     8   19   19     52      7
68    2017/1/11 19:46:9   36  positive  2017     1   11   19     46      9
69   2017/8/25 14:42:22   30  positive  2017     8   25   14     42     22
70     2018/6/4 3:11:55   17  negative  2018     6    4    3     11     55
71    2017/10/2 6:15:35   46  negative  2017    10    2    6     15     35
72    2017/2/15 1:10:53   36  negative  2017     2   15    1     10     53
73    2018/1/5 16:34:19   25  positive  2018     1    5   16     34     19
74   2017/12/21 10:41:2   31  positive  2017    12   21   10     41      2
76    2018/5/2 13:57:30   43  positive  2018     5    2   13     57     30
77   2018/1/20 23:40:31   44  positive  2018     1   20   23     40     31
78   2018/2/27 23:23:20   21  positive  2018     2   27   23     23     20
80      2017/1/26 5:6:5   29  negative  2017     1   26    5      6      5
81  2019/12/11 10:55:16   41  positive  2019    12   11   10     55     16
82     2018/4/9 4:30:48   50  negative  2018     4    9    4     30     48
84    2019/4/27 4:39:34   16  negative  2019     4   27    4     39     34
85     2018/6/26 7:2:57   36  negative  2018     6   26    7      2     57
86     2018/9/6 4:42:59   13  negative  2018     9    6    4     42     59
88    2019/1/2 20:52:52   44  positive  2019     1    2   20     52     52
89    2017/12/24 1:19:7   10  negative  2017    12   24    1     19      7
90    2018/2/6 13:47:11   37  positive  2018     2    6   13     47     11
91    2017/9/19 9:30:48  150  positive  2017     9   19    9     30     48
92    2019/11/14 5:41:6   31  negative  2019    11   14    5     41      6
93  2017/12/15 11:44:25   34  positive  2017    12   15   11     44     25
94    2019/3/10 0:41:34   42  negative  2019     3   10    0     41     34
95    2017/3/11 8:10:58   12  positive  2017     3   11    8     10     58
96    2018/9/17 9:12:59   26  positive  2018     9   17    9     12     59
97   2019/4/13 18:55:54   23  positive  2019     4   13   18     55     54
98    2018/2/20 3:18:26   28  negative  2018     2   20    3     18     26
99    2017/4/23 13:53:6   20  positive  2017     4   23   13     53      6

[96 rows x 9 columns]

In [31]:
df = df[['Sentiment', 'Age', 'Year', 'Month', 'Date', 'Hour', 'Minute', 'Second']]
df

   Sentiment  Age  Year Month Date Hour Minute Second
0   negative   41  2017     3   14    8     34     48
1   positive   31  2017    10    5    9     56     51
2   positive   22  2018     6   15   14     28      5
3   positive   18  2018     6    5   17     36     32
4   negative   12  2018     9   25    7     46     23
5   positive   43  2019     7    4   20     11     33
6   negative   49  2017    11   24    8     58     27
7   positive   13  2019    12   14   15     15     41
8   negative   30  2018    12    1    5     37     10
9   positive   47  2017    10   14   23     25     42
10  positive   47  2017     4   13    9     37      6
11  positive   29  2019     3   13   12     43     35
12  positive   18  2019     8   14   17     32      8
13  positive   29  2018     4   21   16     12     40
14  negative   28  2018    11   23    2     18     59
15  positive   41  2017     1   25   20      1      4
16  negative   27  2017    12    8    6      1     21
17  positive   46  2017    12    3   18      0     44
18  positive   38  2019     8   24   17     25     58
19  negative   12  2018     9   10    3     59     15
20  negative   49  2019    12   14    5     28      8
21  positive   42  2019     4    6   14     51     26
22  positive   10  2019     5    4   21     41     19
23  positive   18  2019     2   28   11     56     35
24  negative   33  2018     8   26    6     16     44
25  negative   37  2018     6   24    5      7     25
26  positive   18  2019     7    7   11     25      7
27  negative   28  2019     2   15    6     37     14
28  positive   32  2017     1    1   12     43      7
29  positive   26  2017     1   22   19     52     30
..       ...  ...   ...   ...  ...  ...    ...    ...
66  positive   35  2017     2   13   13     19     20
67  positive   50  2019     8   19   19     52      7
68  positive   36  2017     1   11   19     46      9
69  positive   30  2017     8   25   14     42     22
70  negative   17  2018     6    4    3     11     55
71  negative   46  2017    10    2    6     15     35
72  negative   36  2017     2   15    1     10     53
73  positive   25  2018     1    5   16     34     19
74  positive   31  2017    12   21   10     41      2
76  positive   43  2018     5    2   13     57     30
77  positive   44  2018     1   20   23     40     31
78  positive   21  2018     2   27   23     23     20
80  negative   29  2017     1   26    5      6      5
81  positive   41  2019    12   11   10     55     16
82  negative   50  2018     4    9    4     30     48
84  negative   16  2019     4   27    4     39     34
85  negative   36  2018     6   26    7      2     57
86  negative   13  2018     9    6    4     42     59
88  positive   44  2019     1    2   20     52     52
89  negative   10  2017    12   24    1     19      7
90  positive   37  2018     2    6   13     47     11
91  positive  150  2017     9   19    9     30     48
92  negative   31  2019    11   14    5     41      6
93  positive   34  2017    12   15   11     44     25
94  negative   42  2019     3   10    0     41     34
95  positive   12  2017     3   11    8     10     58
96  positive   26  2018     9   17    9     12     59
97  positive   23  2019     4   13   18     55     54
98  negative   28  2018     2   20    3     18     26
99  positive   20  2017     4   23   13     53      6

[96 rows x 8 columns]

In [32]:
df.corr()

Empty DataFrame
Columns: []
Index: []